"""add icp_configs table

Revision ID: b8207c2e3983
Revises: dfae5d3bb7b7
Create Date: 2026-08-24 15:56:32.098743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8207c2e3983'
down_revision: Union[str, Sequence[str], None] = 'dfae5d3bb7b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icp_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('target_industries', sa.String(length=500), nullable=True),
    sa.Column('industry_weight', sa.Float(), nullable=False),
    sa.Column('employee_count_min', sa.Integer(), nullable=True),
    sa.Column('employee_count_max', sa.Integer(), nullable=True),
    sa.Column('employee_count_weight', sa.Float(), nullable=False),
    sa.Column('target_revenue_ranges', sa.String(length=500), nullable=True),
    sa.Column('revenue_range_weight', sa.Float(), nullable=False),
    sa.Column('title_keywords', sa.String(length=500), nullable=True),
    sa.Column('title_weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('icp_configs')
    # ### end Alembic commands ###
