"""add company, contact, enrichment_job, waterfall_config models

Revision ID: dfae5d3bb7b7
Revises: 
Create Date: 2026-08-24 15:33:48.866232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfae5d3bb7b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('revenue_range', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=True)
    op.create_table('waterfall_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_type', sa.Enum('EMAIL', 'PHONE', 'COMPANY', name='fieldtype', native_enum=False, length=20), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('priority_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_type', 'provider_name', name='uq_waterfall_config_field_provider'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_waterfall_configs_field_type'), 'waterfall_configs', ['field_type'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('enrichment_status', sa.Enum('PENDING', 'ENRICHED', 'FAILED', name='enrichmentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('icp_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_table('enrichment_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('field_type', sa.Enum('EMAIL', 'PHONE', 'COMPANY', name='fieldtype', native_enum=False, length=20), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAIL', name='jobstatus', native_enum=False, length=10), nullable=False),
    sa.Column('credits_used', sa.Float(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_jobs_contact_id'), 'enrichment_jobs', ['contact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrichment_jobs_contact_id'), table_name='enrichment_jobs')
    op.drop_table('enrichment_jobs')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_waterfall_configs_field_type'), table_name='waterfall_configs')
    op.drop_table('waterfall_configs')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
